version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: wastrachan/dhcpd
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install deps
          command: |
            apk --no-cache add curl
      - run:
          name: Build image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - deploy:
          name: Publish image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              docker push $IMAGE_NAME:latest
            fi
workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            branches:
              only: master
